/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const PlNotification: typeof import('play-ui/src/index')['PlNotification']
}
