/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    PlBadge: typeof import('play-ui/components')['PlBadge']
    PlButton: typeof import('play-ui/components')['PlButton']
    PlCheckbox: typeof import('play-ui/components')['PlCheckbox']
    PlDropdown: typeof import('play-ui/components')['PlDropdown']
    PlIcon: typeof import('play-ui/components')['PlIcon']
    PlInput: typeof import('play-ui/components')['PlInput']
    PlModal: typeof import('play-ui/components')['PlModal']
    PlTables: typeof import('play-ui/components')['PlTables']
  }
}
