/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    copy: typeof import('./src/components/drawer copy.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    Dropdown: typeof import('./src/components/dropdown.vue')['default']
    Message: typeof import('./src/components/message.vue')['default']
    Modal: typeof import('./src/components/modal.vue')['default']
    Notification: typeof import('./src/components/notification.vue')['default']
    PlAlert: typeof import('play-ui/index')['PlAlert']
    PlBadge: typeof import('play-ui/components')['PlBadge']
    Plbutton: typeof import('play-ui/index')['Plbutton']
    PlButton: typeof import('play-ui/index')['PlButton']
    PlButtonGroup: typeof import('play-ui/index')['PlButtonGroup']
    PlCheckbox: typeof import('play-ui/components')['PlCheckbox']
    PlDrawer: typeof import('play-ui/index')['PlDrawer']
    PlDropdown: typeof import('play-ui/index')['PlDropdown']
    PlIcon: typeof import('play-ui/index')['PlIcon']
    PlInput: typeof import('play-ui/components')['PlInput']
    PlModal: typeof import('play-ui/index')['PlModal']
    PlPopover: typeof import('play-ui/index')['PlPopover']
    PlPrompt: typeof import('play-ui')['PlPrompt']
    PlScroll: typeof import('play-ui/index')['PlScroll']
    PlScrollbar: typeof import('play-ui/index')['PlScrollbar']
    PlStep: typeof import('play-ui/index')['PlStep']
    PlSteps: typeof import('play-ui/index')['PlSteps']
    PlTables: typeof import('play-ui/components')['PlTables']
    PlTabPane: typeof import('play-ui/index')['PlTabPane']
    PlTabs: typeof import('play-ui/index')['PlTabs']
    PlTooltip: typeof import('play-ui/index')['PlTooltip']
    Popover: typeof import('./src/components/popover.vue')['default']
    Scrollbar: typeof import('./src/components/scrollbar.vue')['default']
    Steps: typeof import('./src/components/steps.vue')['default']
    Tabs: typeof import('./src/components/tabs.vue')['default']
    Tooltip: typeof import('./src/components/tooltip.vue')['default']
  }
}
