/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DemoBlock: typeof import('./src/components/demo-block.vue')['default']
    PlButton: typeof import('play-vue')['PlButton']
    PlButtonGroup: typeof import('play-vue')['PlButtonGroup']
    PlIcon: typeof import('play-vue')['PlIcon']
    PlTag: typeof import('play-vue')['PlTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
