/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PlAlert: typeof import('play-ui')['PlAlert']
    PlButton: typeof import('play-ui')['PlButton']
    PlModal: typeof import('play-ui')['PlModal']
  }
}
