/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const PlMessage: typeof import('play-ui')['PlMessage']
  const PlNotification: typeof import('play-ui')['PlNotification']
}
