/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PlAlert: typeof import('play-vue')['PlAlert']
    PlBadge: typeof import('play-vue/components/index')['PlBadge']
    PlButton: typeof import('play-vue/components/index')['PlButton']
    PlButtonGroup: typeof import('play-vue/components/index')['PlButtonGroup']
    PlIcon: typeof import('play-vue/components/index')['PlIcon']
    PlModal: typeof import('play-vue/components/index')['PlModal']
    PlTag: typeof import('play-vue')['PlTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
