/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PlAlert: typeof import('play-ui')['PlAlert']
    PlBadge: typeof import('play-ui')['PlBadge']
    PlBreadcrumb: typeof import('play-ui')['PlBreadcrumb']
    PlButton: typeof import('play-ui')['PlButton']
    PlButtonGroup: typeof import('play-ui')['PlButtonGroup']
    PlDrawer: typeof import('play-ui')['PlDrawer']
    PlDropdown: typeof import('play-ui')['PlDropdown']
    PlIcon: typeof import('play-ui')['PlIcon']
    PlInput: typeof import('play-ui')['PlInput']
    PlModal: typeof import('play-ui')['PlModal']
    PlPopover: typeof import('play-ui')['PlPopover']
    PlSelect: typeof import('play-ui')['PlSelect']
    PlSteps: typeof import('play-ui')['PlSteps']
    PlTabPane: typeof import('play-ui')['PlTabPane']
    PlTabs: typeof import('play-ui')['PlTabs']
    PlTag: typeof import('play-ui')['PlTag']
    PlTooltip: typeof import('play-ui')['PlTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
